"use client";

import { FormEvent, useState } from "react";
import { ArrowLeftIcon, ArrowRightIcon, CheckIcon } from "@heroicons/react/24/outline";
import type { Lang } from "@/lib/content";

export function QuoteForm({ lang }: { lang: Lang }) {
  const [step, setStep] = useState(0); const [done, setDone] = useState(false); const da = lang === "da";
  const next = (e: FormEvent) => { e.preventDefault(); if (step < 2) setStep(step + 1); else setDone(true); };
  if (done) return <div className="flex min-h-[380px] flex-col items-start justify-center rounded-3xl bg-white p-8 text-[var(--ink)]"><span className="mb-6 flex h-14 w-14 items-center justify-center rounded-full bg-[var(--signal)]"><CheckIcon className="h-7"/></span><h3 className="text-3xl font-medium">{da ? "Tak — oplysningerne er klar." : "Thank you — your details are ready."}</h3><p className="mt-4 max-w-md text-black/60">{da ? "E-mailafsendelse tilkobles, når vi vælger formularløsningen. Indtil da er dette en sikker demo." : "Email delivery will be connected when we choose the form service. Until then, this is a safe demo."}</p><button onClick={() => {setDone(false);setStep(0)}} className="mt-8 underline">{da ? "Start igen" : "Start over"}</button></div>;
  return <form onSubmit={next} className="min-h-[430px] rounded-3xl bg-white p-6 text-[var(--ink)] md:p-9">
    <div className="mb-10 flex items-center justify-between"><span className="eyebrow">{da ? "Forespørgsel" : "Inspection request"}</span><span className="text-sm text-black/45">0{step + 1} / 03</span></div>
    {step === 0 && <fieldset><legend className="mb-2 text-3xl font-medium tracking-tight">{da ? "Hvad skal vi inspicere?" : "What should we inspect?"}</legend><p className="mb-7 text-sm leading-6 text-black/50">{da ? "Udfyld begge felter, så vi kan vurdere opgaven." : "Complete both fields so we can assess the assignment."}</p><div className="grid gap-4"><div className="rounded-2xl border border-black/10 bg-[var(--snow)] p-4 transition focus-within:border-[var(--forest)] focus-within:ring-2 focus-within:ring-[var(--forest)]/10"><label htmlFor="turbine-count" className="mb-2 block text-sm font-semibold">{da ? "Antal vindmøller" : "Number of turbines"}</label><input id="turbine-count" name="turbineCount" required type="number" min="1" inputMode="numeric" placeholder={da ? "F.eks. 12" : "E.g. 12"} className="w-full border-0 bg-transparent p-0 text-lg outline-none placeholder:text-black/30"/></div><div className="rounded-2xl border border-black/10 bg-[var(--snow)] p-4 transition focus-within:border-[var(--forest)] focus-within:ring-2 focus-within:ring-[var(--forest)]/10"><label htmlFor="site-location" className="mb-2 block text-sm font-semibold">{da ? "Placering" : "Location"}</label><input id="site-location" name="location" required autoComplete="address-level2" placeholder={da ? "By, region eller koordinater" : "City, region or coordinates"} className="w-full border-0 bg-transparent p-0 text-lg outline-none placeholder:text-black/30"/></div></div></fieldset>}
    {step === 1 && <fieldset><legend className="mb-7 text-3xl font-medium tracking-tight">{da ? "Hvad har I brug for?" : "What do you need?"}</legend><div className="grid gap-3">{(da ? ["Visuel inspektion","Termografi","Kortlægning","Komplet rapport"] : ["Visual inspection","Thermal imaging","Mapping","Complete report"]).map((x, i)=><label key={x} className="flex cursor-pointer items-center gap-4 rounded-xl border border-black/15 p-4 hover:border-[var(--forest)]"><input name="service" type="checkbox" defaultChecked={i===0}/><span>{x}</span></label>)}</div></fieldset>}
    {step === 2 && <fieldset><legend className="mb-7 text-3xl font-medium tracking-tight">{da ? "Hvordan kontakter vi jer?" : "How can we reach you?"}</legend><label className="mb-3 block text-sm">{da ? "Navn" : "Name"}</label><input required className="w-full rounded-xl border border-black/20 p-4"/><label className="mb-3 mt-5 block text-sm">E-mail</label><input required type="email" className="w-full rounded-xl border border-black/20 p-4"/></fieldset>}
    <div className="mt-10 flex items-center justify-between">{step > 0 ? <button type="button" onClick={()=>setStep(step-1)} className="flex items-center gap-2 text-sm"><ArrowLeftIcon className="h-4"/>{da ? "Tilbage" : "Back"}</button> : <span/>}<button className="flex items-center gap-3 rounded-full bg-[var(--ink)] px-6 py-4 text-sm font-semibold text-white">{step === 2 ? (da ? "Gennemfør" : "Complete") : (da ? "Fortsæt" : "Continue")}<ArrowRightIcon className="h-4"/></button></div>
  </form>;
}
